[workspace]
resolver = "2"
members = [
    "src/core-ltx",    # Functional core: all llms.txt generation logic + CLI program for one-offs (generation + update).
    "src/api-ltx",     # API webserver + DB setup.
    "src/cli-ltx",     # CLI client for users: interfaces with API.
    "src/front-ltx",   # Webapp frontend for users: interfaces with API.
    "src/worker-ltx",  # Backend worker executing logic (generation + update) from API sever into database.
    "src/cron-ltx",    # Cron worker service to perodically update websites' llms.txt.
    "src/common-ltx"   # Catch-all for utilities common to all crates.
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Malcolm Greaves <75upbeats_hybrids@icloud.com>"]
license = "Mozilla Public License 2.0"
readme = "README.md"
