[package]
name = "worker-ltx"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Backend worker executing logic (generation + update) from API sever into database."

[dependencies]
