[target.aarch64-apple-darwin]
rustflags = [
  "-L", "/opt/homebrew/opt/libpq/lib",
  "-L", "/opt/homebrew/lib",
]

[target.aarch64-apple-darwin.env]
PQ_LIB_DIR = "/opt/homebrew/opt/libpq/lib"

[target.x86_64-apple-darwin.env]
PQ_LIB_DIR = "/opt/homebrew/opt/libpq/lib"
