[package]
name = "api-ltx"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "API webserver + DB setup."

[dependencies]
